USE [LUNA_GAMEDB_2025]
GO
/****** Object:  StoredProcedure [dbo].[MP_CHARACTER_HeroInfoUPdate]    Script Date: 8/14/2025 12:20:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
080530 LUJ, ?? ?? 0? ?? ?? ??? ??????? ?
*/
ALTER   proc [dbo].[MP_CHARACTER_HeroInfoUPdate]
(
	@CHARACTER_IDX				int
,	@CHARACTER_STR				int
,	@CHARACTER_MANA				int	
,	@CHARACTER_DEX				int
,	@CHARACTER_VIT				int
,	@CHARACTER_INT				int
,	@CHARACTER_WIS				int
,	@CHARACTER_FAME				smallint
,	@CHARACTER_KARMA			tinyint

-- 080604 LYW --- MP_CHARACTER_HeroInfoUpdate : ??? ??? bigint? ?????, 
-- ?????? int? ???? ?? bigint? ???
--,	@CHARACTER_EXPOINT			int
,	@CHARACTER_EXPOINT			bigint

,	@CHARACTER_GRADEUPPOINT		smallint
,	@CHARACTER_MONEY			bigint
,	@CHARACTER_QUICKPACE		int
,	@CHARACTER_ABILITYEXP		int
,	@CHARACTER_PLAYTIME			int
,	@CHARACTER_LASTPKENDTIME	int
,	@CHARACTER_MAXGRADE			tinyint
)

as
	Set Nocount on
--	Set Xact_Abort on

	declare @Cur_Date datetime
	Set @Cur_Date = getdate()
	
	-- 080530 LUJ, ??? 0? ?? ?? ??? ???
	IF 0 = @CHARACTER_MAXGRADE
	BEGIN
		SELECT	@CHARACTER_MAXGRADE = CHARACTER_MAXGRADE
		FROM	TB_CHARACTER
		WHERE	CHARACTER_IDX = @CHARACTER_IDX
	END
	
	update 	TB_CHARACTER 	set			
			CHARACTER_STR			=	@CHARACTER_STR
		,	CHARACTER_MANA			=	@CHARACTER_MANA
		,	CHARACTER_DEX			= 	@CHARACTER_DEX
		,	CHARACTER_VIT			= 	@CHARACTER_VIT
		,	CHARACTER_INT			=	@CHARACTER_INT
		,	CHARACTER_WIS			=	@CHARACTER_WIS
		,	CHARACTER_FAME			=	@CHARACTER_FAME
		,	CHARACTER_KARMA			=	@CHARACTER_KARMA
		,	CHARACTER_EXPOINT			=	@CHARACTER_EXPOINT
		,	CHARACTER_GRADEUPPOINT		= 	@CHARACTER_GRADEUPPOINT
		,	CHARACTER_MONEY			=	@CHARACTER_MONEY
--		, 	CHARACTER_ABILITYEXP		= 	@CHARACTER_ABILITYEXP
		,	CHARACTER_PLAYTIME		=	@CHARACTER_PLAYTIME
		,	CHARACTER_LASTPKENDTIME	=	@CHARACTER_LASTPKENDTIME
		,	CHARACTER_LASTMODIFIED		=	@Cur_date
		,	CHARACTER_MAXGRADE		=	@CHARACTER_MAXGRADE

		where CHARACTER_IDX = @CHARACTER_IDX
