USE [LUNA_GAMEDB_2025]
GO
/****** Object:  StoredProcedure [dbo].[MP_GUILD_ADD_SKILL]    Script Date: 8/14/2025 1:02:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
080417 LUJ, 길드 스킬 획득
*/

ALTER PROCEDURE [dbo].[MP_GUILD_ADD_SKILL]
(
	@GUILD_IDX		INT,
	-- 080417 LUJ, 스킬 습득에 필요한 길드 포인트
	@NEEDED_SCORE	FLOAT,
	@NEEDED_MONEY	INT,
	@NULL		INT,
	@SKILL_IDX	INT,
	@SKILL_LEVEL	INT
)
AS
	SET NOCOUNT ON
	
	-- 080417 LUJ, 포인트 갱신

		-- Ariya Pogi Guild Skill Fix 09/09/2022
	IF NOT EXISTS ( SELECT 1 FROM TB_GUILD WHERE	GUILDIDX = @GUILD_IDX AND SCORE > @NEEDED_SCORE)
	BEGIN
		SELECT 0
		RETURN
	END
	ELSE
	BEGIN
		UPDATE	TB_GUILD
		SET		SCORE = SCORE - @NEEDED_SCORE
		WHERE	GUILDIDX = @GUILD_IDX AND SCORE > @NEEDED_SCORE
	END

		
		
	
	

	IF NOT EXISTS (SELECT 1 FROM TB_GUILD_SKILL WHERE	GUILD_IDX = @GUILD_IDX AND SKILL_IDX = @SKILL_IDX)
	BEGIN
		INSERT	TB_GUILD_SKILL
				( GUILD_IDX, SKILL_IDX, SKILL_LEVEL )
		VALUES	( @GUILD_IDX, @SKILL_IDX, @SKILL_LEVEL )
	END
	ELSE
	BEGIN
		UPDATE	TB_GUILD_SKILL
		SET		SKILL_LEVEL = @SKILL_LEVEL
		WHERE	GUILD_IDX = @GUILD_IDX AND SKILL_IDX = @SKILL_IDX
	END
	

	SELECT	@SKILL_IDX, @SKILL_LEVEL, @NEEDED_MONEY, CAST( SCORE AS INT )
	FROM	TB_GUILD
	WHERE	GUILDIDX = @GUILD_IDX
	
	RETURN

