USE [LUNA_GAMEDB_2025]
GO

/****** Object:  Table [dbo].[SIEGEWARFARE_WATERSEED_COMPLETE]    Script Date: 24/08/2025 11:14:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SIEGEWARFARE_WATERSEED_COMPLETE](
	[ID_IDX] [int] IDENTITY(1,1) NOT NULL,
	[P_IDX] [int] NOT NULL,
	[MAPTYPE] [int] NOT NULL,
	[GUILDIDX] [int] NOT NULL,
 CONSTRAINT [PK_SIEGEWARFARE_WATERSEED_COMPLETE] PRIMARY KEY CLUSTERED 
(
	[ID_IDX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


