USE [LUNA_LOGDB_2025]
GO

/****** Object:  Table [dbo].[TB_SKILL_HACK_LOG]    Script Date: 8/14/2025 1:30:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_SKILL_HACK_LOG](
	[LOG_IDX] [int] IDENTITY(1,1) NOT NULL,
	[CHAR_IDX] [int] NOT NULL,
	[KIND_TYPE] [varchar](16) NOT NULL,
	[DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_SKILL_HACK_LOG] ADD  CONSTRAINT [DF_TB_SKILL_HACK_LOG_SCRIPT]  DEFAULT ('') FOR [KIND_TYPE]
GO

ALTER TABLE [dbo].[TB_SKILL_HACK_LOG] ADD  CONSTRAINT [DF_TB_SKILL_HACK_LOG_DATE]  DEFAULT (getdate()) FOR [DATE]
GO


