USE [LUNA_LOGDB_2025]
GO
/****** Object:  StoredProcedure [dbo].[TP_SKILL_HACK_LOG_INSERT]    Script Date: 8/14/2025 1:30:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
090109 LUJ, ???? ?? ??? ????
*/
CREATE PROCEDURE [dbo].[TP_SKILL_HACK_LOG_INSERT]
(
	@CHAR_IDX	INT,
	@KIND_TYPE	VARCHAR( 16 ) = ''
)
AS
	SET NOCOUNT ON
	--RETURN
	INSERT	INTO	TB_SKILL_HACK_LOG
					( CHAR_IDX, KIND_TYPE )
	VALUES			( @CHAR_IDX, @KIND_TYPE )
	RETURN


